# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.9.2

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest
  - postgres:latest

variables:
  POSTGRES_DB: database_name

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

# To get Django tests to work you may need to create a settings file using
# the following DATABASES:
#
# DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'ci',
#        'USER': 'postgres',
#        'PASSWORD': 'postgres',
#        'HOST': 'postgres',
#        'PORT': '5432',
#    },
# }
#
# and then adding `--settings app.settings.ci` (or similar) to the test command
stages:
  - test
  - deploy

UnitTest:
  stage: test
  before_script:
    - python -V
    - cd backend/secfit
    - apt-get update -qy
    - pip install -r requirements.txt
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - python manage.py test workouts
    - python manage.py test users

Deployment:
    type: deploy
    stage: deploy
    image: ruby:2.4
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APPNAME_BACKEND --api-key=$HEROKU_API_KEY
        - dpl --provider=heroku --app=$HEROKU_APPNAME_FRONTEND --api-key=$HEROKU_API_KEY
        - export HEROKU_API_KEY=$HEROKU_APIKEY
    only:
        - master
    #environment:
     # name: production
      #url: $HEROKU_APP_HOST
